## Day 1

In [2]:
using Pkg
using BenchmarkTools

In [4]:
file = open("input1.txt")
lines = readlines(file)
lines = parse.(Float64,lines)

988-element Array{Float64,1}:
     13.0
      9.0
      8.0
      1.0
    -15.0
     10.0
     16.0
     17.0
      8.0
      8.0
     17.0
      6.0
     17.0
      ⋮  
      3.0
    -16.0
     26.0
     20.0
   -221.0
     -6.0
     30.0
    -51.0
    470.0
 -67792.0
      3.0
 135555.0

**Part 1**: Starting with a frequency of zero, what is the resulting frequency after all of the changes in frequency have been applied?

In [3]:
sum(lines)

493.0

**Part2**: In this example, the first frequency reached twice is 2. Note that your device might need to repeat its list of frequency changes many times before a duplicate frequency is found, and that duplicates might be found while in the middle of processing the list.

Here are other examples:

+1, -1 first reaches 0 twice.
+3, +3, +4, -2, -4 first reaches 10 twice.
-6, +3, +8, +5, -6 first reaches 5 twice.
+7, +7, -2, -7, -4 first reaches 14 twice.
What is the first frequency your device reaches twice?

In [12]:
function part2(data::Array{Int,1})::Int
    freq_set = Set{Int}()
    freq_found = 0
    run_sum = 0.0
    while freq_found == 0
        for freq in data
            run_sum += freq
            if in(run_sum, freq_set)
                return run_sum
                freq_found += 1
                break
            else
                push!(freq_set, run_sum)
            end
        end
    end
end

@btime part2(lines)

  4.552 ms (33 allocations: 3.00 MiB)


413.0

In [6]:
function part2_dict(data::Array{Float64})
    freq_dict = Dict{Float64,Float64}()
    freq_found = 0
    run_sum = 0.0
    while freq_found == 0
        for freq in data
            run_sum += freq
            if haskey(freq_dict, run_sum)
                return run_sum
                freq_found += 1
                break
            else
                freq_dict[run_sum] = freq
            end
        end
    end
end

@btime part2_dict(lines)

  4.901 ms (37 allocations: 5.67 MiB)


413.0

In [10]:
function part2_dict(data::Array{Int,1})::Int
    freq_dict = Dict{Int,Bool}()
    freq_found = 0
    run_sum = 0.0
    while freq_found == 0
        for freq in data
            run_sum += freq
            if haskey(freq_dict, run_sum)
                return run_sum
                freq_found += 1
                break
            else
                freq_dict[run_sum] = true
            end
        end
    end
end

@btime part2_dict(lines)

  5.714 ms (36 allocations: 3.34 MiB)


413.0

## Day2

In [44]:
file_2 = open("input2.txt")
lines_2 = readlines(file_2)

250-element Array{String,1}:
 "lutrogkbetprmshdyfiqvzixaw"
 "lujnmgkbetprmshdyicqvzivaw"
 "lujnogkbetprmshdyfkqvtpxaw"
 "lujnqgkbetpmmshdywcqvzixaw"
 "lujnogtaetprmshdyffqvzixaw"
 "lujnogkbetprmuldyfcqvqixaw"
 "luunogkbetprlshdyfcqrzixaw"
 "lujnogkketprmshdyhcqvtixaw"
 "lyjnogzbetprmsbdyfcqvzixaw"
 "eujnogkbetprmshdyfrqvzixmw"
 "lujnogcbetprmshdyfvqvziqaw"
 "lujnogkbempruahdyfcqvzixaw"
 "lujlogkbetprmlhdyfyqvzixaw"
 ⋮                           
 "lujnogkbeturmshgymcqvzixaw"
 "lujiogkbbrprmshdyfcqvzixaw"
 "yujnogkbutprmshdyfcqvzixab"
 "lujvofubetprmshdyfcqvzixaw"
 "lujwogkbrtprmshdyfcqvnixaw"
 "lusnogkbetprmsydyfcqvzikaw"
 "lujnolkbewprmshdyfyqvzixaw"
 "lujnogkbetprvshdyfcivzikaw"
 "lujnogxbetprmszdyfzqvzixaw"
 "lujnogkvetprmxhdydcqvzixaw"
 "lujnogkbetpimsrdwfcqvzixaw"
 "lujnomboetprmshdyfcqvzixaw"

In [201]:
no_2 = 0
no_3 = 0
for line in lines_2
    for l in Set(line)
        if count(j->(j==l),line) == 3
            no_3 += 1
            break
        end
    end
    for l in Set(line)
        if count(j->(j==l),line) == 2
            no_2 += 1
            break
        end
    end
end
println(no_2," and ", no_3)
println("Product is ", no_2*no_3)

247 and 39
Product is 9633


**Part2**
Confident that your list of box IDs is complete, you're ready to find the boxes full of prototype fabric.

The boxes will have IDs which differ by exactly one character at the same position in both strings. For example, given the following box IDs:

abcde
fghij
klmno
pqrst
fguij
axcye
wvxyz
The IDs abcde and axcye are close, but they differ by two characters (the second and fourth). However, the IDs fghij and fguij differ by exactly one character, the third (h and u). Those must be the correct boxes.

What letters are common between the two correct box IDs? (In the example above, this is found by removing the differing character from either ID, producing fgij.)

In [122]:
function d2_p2(data::Array{String,1})
    for line in data
        for j in data
            position_diff = 0
            for i in 1:length(line)
                position_diff += Int(line[i]!= j[i])
                if position_diff > 1
                    break
                end
            end
            if position_diff == 1
                string_ret = []
                for i in 1:length(line)
                    if line[i] == j[i]
                       push!(string_ret,line[i])
                    end
                end
                return(join(string_ret))
            end
        end
    end
end

@btime d2_p2(lines_2)

  358.082 μs (12 allocations: 1.00 KiB)


"lujnogabetpmsydyfcovzixaw"

In [135]:
function d2_p2_vec(data::Array{String,1})
    for line in data
        for j in data
            diff_bool = [i for i in line] .== [i for i in j]
            sum_diff = sum(.!diff_bool)
            if sum_diff == 1
                string_ret = line[collect(1:length(line))[diff_bool]]
                return(string_ret)
            end
        end
    end
end

@btime d2_p2_vec(lines_2)

  8.549 ms (74834 allocations: 39.33 MiB)


"lujnogabetpmsydyfcovzixaw"

In [133]:
?rsplit

search: rsplit



```
rsplit(s::AbstractString; limit::Integer=0, keepempty::Bool=false)
rsplit(s::AbstractString, chars; limit::Integer=0, keepempty::Bool=true)
```

Similar to [`split`](@ref), but starting from the end of the string.

# Examples

```jldoctest
julia> a = "M.a.r.c.h"
"M.a.r.c.h"

julia> rsplit(a,".")
5-element Array{SubString{String},1}:
 "M"
 "a"
 "r"
 "c"
 "h"

julia> rsplit(a,".";limit=1)
1-element Array{SubString{String},1}:
 "M.a.r.c.h"

julia> rsplit(a,".";limit=2)
2-element Array{SubString{String},1}:
 "M.a.r.c"
 "h"
```


In [131]:
split("abc","")

3-element Array{SubString{String},1}:
 "a"
 "b"
 "c"